# Generated by Django 5.2.12 on 2026-05-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staff",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="staff",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
