# Generated by Django 5.2.9 on 2025-12-05 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='shops/covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_online_booking', models.BooleanField(default=True)),
                ('booking_lead_time', models.PositiveIntegerField(default=60, help_text='Minimum minutes before an appointment can be booked')),
                ('max_advance_booking_days', models.PositiveIntegerField(default=30, help_text='Maximum days in advance a booking can be made')),
                ('buffer_time', models.PositiveIntegerField(default=0, help_text='Buffer time in minutes between appointments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='shops.shop')),
            ],
            options={
                'verbose_name_plural': 'Business hours',
                'ordering': ['day_of_week'],
                'unique_together': {('shop', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='ShopClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('is_full_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='shops.shop')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('shop', 'date')},
            },
        ),
    ]
