# Generated by Django 5.2.12 on 2026-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_payment_status_booking_stripe_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
