# Generated by Django 5.2.12 on 2026-06-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_followup"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="followup_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
